name: Run Node Projects
on:
  push:
    branches: [main]
  schedule:
    - cron: '*/5 * * * *'  # 每5分钟执行一次
  workflow_dispatch:

jobs:
  run_index1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Run index1.js
        run: node index1.js

  run_index2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Run index2.js
        run: node index2.js
